// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Data from "./Data.bs.js";
import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as SVGJsx from "./SVG.jsx";
import ToneJs from "./Tone.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as IconsJsx from "./Icons.jsx";
import AboutJsx from "./about.jsx";
import * as Belt_MapInt from "rescript/lib/es6/belt_MapInt.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as DataGeneration from "./DataGeneration.bs.js";
import * as Bs from "react-icons/bs";
import * as Fa from "react-icons/fa";
import NotePlayerJs from "./NotePlayer.js";

function join(__x) {
  return __x.join(" ");
}

function str(prim) {
  return prim;
}

var reactMap = Belt_Array.map;

var reactMapWithIndex = Belt_Array.mapWithIndex;

var make = IconsJsx.Logo;

var Logo = {
  make: make
};

var make$1 = SVGJsx.SVG;

var SVG = {
  make: make$1
};

var Symmetry = {};

var ChevronDown = {};

var ChevronUp = {};

var PlayIcon = {};

function App$Collapsed(Props) {
  var render = Props.render;
  var match = React.useState(function () {
        return true;
      });
  return Curry._2(render, match[0], match[1]);
}

var Collapsed = {
  make: App$Collapsed
};

var pitchKeys = [
  "C",
  "C♯ D♭",
  "D",
  "D♯ E♭",
  "E",
  "F",
  "F♯ G♭",
  "G",
  "G♯ A♭",
  "A",
  "A♯ B♭",
  "B"
];

var pitchKeysShort = [
  "C",
  "C♯",
  "D",
  "D♯",
  "E",
  "F",
  "F♯",
  "G",
  "G♯",
  "A",
  "A♯",
  "B"
];

var semitones = [
  "0",
  "1",
  "2",
  "3",
  "4",
  "5",
  "6",
  "7",
  "8",
  "9",
  "10",
  "11"
];

var mMPs = [
  "P1",
  "m2",
  "M2",
  "m3",
  "M3",
  "P4",
  "TT",
  "P5",
  "m6",
  "M6",
  "m7",
  "M7"
];

var dimAugs = [
  "d2",
  "A1",
  "d3",
  "A2",
  "d4",
  "A3",
  "TT",
  "d6",
  "A5",
  "d7",
  "A6",
  "d8"
];

var IntervalRefs = {
  pitchKeys: pitchKeys,
  pitchKeysShort: pitchKeysShort,
  semitones: semitones,
  mMPs: mMPs,
  dimAugs: dimAugs
};

function stepsToBits(x) {
  return Belt_Array.reduce(x, "", (function (acc, value) {
                var tmp;
                switch (value) {
                  case 1 :
                      tmp = "1";
                      break;
                  case 2 :
                      tmp = "10";
                      break;
                  case 3 :
                      tmp = "100";
                      break;
                  case 4 :
                      tmp = "1000";
                      break;
                  case 5 :
                      tmp = "10000";
                      break;
                  case 6 :
                      tmp = "100000";
                      break;
                  default:
                    tmp = "";
                }
                return acc + tmp;
              }));
}

function bitsToSemitoneSteps(x) {
  return Belt_Array.sliceToEnd(Belt_Array.map(x.split("1"), (function (a) {
                    return a.length + 1 | 0;
                  })), 1);
}

function bitsToHalfnoteSteps(x) {
  return Belt_Array.sliceToEnd(Belt_Array.map(x.split("1"), (function (a) {
                    var l = a.length + 1 | 0;
                    if (l !== 1) {
                      if (l !== 2) {
                        if (l % 2 === 0) {
                          return String(l / 2 | 0) + "W";
                        } else {
                          return String(l) + "H";
                        }
                      } else {
                        return "W";
                      }
                    } else {
                      return "H";
                    }
                  })), 1);
}

function bitToDisplaySymbol(bit, index, currentKey, currentStepDisplay, bitString) {
  var a;
  switch (currentStepDisplay) {
    case /* Key */0 :
        a = DataGeneration.rotate(pitchKeysShort, currentKey);
        break;
    case /* MinMaj */1 :
        a = mMPs;
        break;
    case /* DimAug */2 :
        a = dimAugs;
        break;
    case /* Semitone */3 :
    case /* SemitoneSteps */4 :
    case /* HalfnoteSteps */5 :
        a = semitones;
        break;
    case /* Binary */6 :
        a = DataGeneration.BitOps.stringToStringArray(bitString);
        break;
    
  }
  if (bit === "0") {
    return "•";
  } else {
    return Belt_Option.getWithDefault(Belt_Array.get(a, index), "");
  }
}

function App$StepButton(Props) {
  var selected = Props.selected;
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("div", {
              className: [
                  selected ? "text-blue-700 border-blue-700 bg-blue-50 font-bold hover:border-blue-700" : "border-black bg-white font-medium border-transparent hover:border-neutral-400 hover:bg-neutral-100",
                  "col-span-1 p-1 rounded-xl px-2 text-center border cursor-default"
                ].join(" "),
              onClick: onClick
            }, children);
}

var StepButton = {
  make: App$StepButton
};

function App$Scale(Props) {
  var bitString = Props.bitString;
  var currentStepDisplay = Props.currentStepDisplay;
  var currentKey = Props.currentKey;
  var kind = Props.kind;
  var x;
  if (currentStepDisplay >= 4) {
    switch (currentStepDisplay) {
      case /* SemitoneSteps */4 :
          x = bitsToSemitoneSteps(bitString).length;
          break;
      case /* HalfnoteSteps */5 :
          x = bitsToHalfnoteSteps(bitString).length;
          break;
      case /* Binary */6 :
          x = 12;
          break;
      
    }
  } else {
    x = 12;
  }
  var gridCols;
  switch (x) {
    case 0 :
        gridCols = "grid-cols-0";
        break;
    case 1 :
        gridCols = "grid-cols-1";
        break;
    case 2 :
        gridCols = "grid-cols-2";
        break;
    case 3 :
        gridCols = "grid-cols-3";
        break;
    case 4 :
        gridCols = "grid-cols-4";
        break;
    case 5 :
        gridCols = "grid-cols-5";
        break;
    case 6 :
        gridCols = "grid-cols-6";
        break;
    case 7 :
        gridCols = "grid-cols-7";
        break;
    case 8 :
        gridCols = "grid-cols-8";
        break;
    case 9 :
        gridCols = "grid-cols-9";
        break;
    case 10 :
        gridCols = "grid-cols-10";
        break;
    case 11 :
        gridCols = "grid-cols-11";
        break;
    case 12 :
        gridCols = "grid-cols-12";
        break;
    default:
      gridCols = "grid-cols-12";
  }
  var container = function (i, content) {
    var tmp;
    switch (kind) {
      case /* Species */0 :
          tmp = " ";
          break;
      case /* Mode */1 :
      case /* NonMode */2 :
          tmp = "";
          break;
      
    }
    return React.createElement("div", {
                key: String(i),
                className: [
                    "col-span-1 flex flex-row items-center justify-center min-w-[2rem]",
                    "",
                    tmp
                  ].join(" ")
              }, content);
  };
  var tmp;
  var exit = 0;
  if (currentStepDisplay >= 4) {
    switch (currentStepDisplay) {
      case /* SemitoneSteps */4 :
          tmp = Belt_Array.mapWithIndex(bitsToSemitoneSteps(bitString), (function (i, step) {
                  return container(i, String(step));
                }));
          break;
      case /* HalfnoteSteps */5 :
          tmp = Belt_Array.mapWithIndex(bitsToHalfnoteSteps(bitString), container);
          break;
      case /* Binary */6 :
          exit = 1;
          break;
      
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    tmp = Belt_Array.mapWithIndex(DataGeneration.BitOps.stringToStringArray(bitString), (function (i, bit) {
            return container(i, bitToDisplaySymbol(bit, i, currentKey, currentStepDisplay, bitString));
          }));
  }
  return React.createElement("div", {
              className: [
                  "flex-1 grid",
                  gridCols
                ].join(" ")
            }, tmp);
}

var Scale = {
  make: App$Scale
};

function App$Species(Props) {
  var currentBits = Props.currentBits;
  var currentStepDisplay = Props.currentStepDisplay;
  var setCurrentBits = Props.setCurrentBits;
  var currentKey = Props.currentKey;
  var speciesId = Props.speciesId;
  var speciesDetails = Props.speciesDetails;
  var scaleLength;
  if (currentStepDisplay >= 4) {
    switch (currentStepDisplay) {
      case /* SemitoneSteps */4 :
          scaleLength = bitsToSemitoneSteps(speciesId).length;
          break;
      case /* HalfnoteSteps */5 :
          scaleLength = bitsToHalfnoteSteps(speciesId).length;
          break;
      case /* Binary */6 :
          scaleLength = DataGeneration.BitOps.stringToStringArray(speciesId).length;
          break;
      
    }
  } else {
    scaleLength = DataGeneration.BitOps.stringToStringArray(speciesId).length;
  }
  Belt_Array.range(1, scaleLength);
  var speciesNameData = Belt_Array.keep(Data.namedSpecies, (function (param) {
          return DataGeneration.any(DataGeneration.getRotations(DataGeneration.BitOps.stringToStringArray(stepsToBits(DataGeneration.BitOps.stringToIntArray(param[0])))), (function (x) {
                        return DataGeneration.BitOps.stringArrayToString(x) === speciesId;
                      }));
        }));
  var speciesNames = Belt_Array.keep(Belt_Array.map(speciesNameData, (function (param) {
                return Belt_Array.keep(Belt_Array.map(param[1], (function (param) {
                                    return param[1];
                                  })), (function (x) {
                                return x !== "";
                              })).join(", ");
              })), (function (x) {
            return x !== "";
          })).join(", ");
  var numModes = Belt_Array.keep(speciesDetails.modes, (function (param) {
          return DataGeneration.startsWith1(DataGeneration.BitOps.stringToStringArray(param[0]));
        })).length;
  var numPitchClasses = speciesDetails.modes.length;
  React.createElement("span", undefined, "(" + String(numModes) + ":" + String(numPitchClasses) + ")");
  return React.createElement(App$Collapsed, {
              render: (function (speciesHidden, setSpeciesHidden) {
                  var anySelected = DataGeneration.any(speciesDetails.modes, (function (param) {
                          var rotation = param[0];
                          return Belt_Option.mapWithDefault(currentBits, false, (function (c) {
                                        return DataGeneration.BitOps.intArrayToString(c) === rotation;
                                      }));
                        }));
                  Belt_Option.mapWithDefault(currentBits, false, (function (c) {
                          return DataGeneration.BitOps.intArrayToString(c) === speciesId;
                        }));
                  var scaleName = String(DataGeneration.BitOps.stringToInt(speciesId));
                  var onClickHeader = function (param) {
                    Belt_Option.mapWithDefault(currentBits, (Curry._1(setSpeciesHidden, (function (param) {
                                  return false;
                                })), Curry._1(setCurrentBits, (function (param) {
                                  return DataGeneration.BitOps.stringToIntArray(speciesId);
                                }))), (function (param) {
                            Curry._1(setSpeciesHidden, (function (param) {
                                    if (speciesHidden) {
                                      return !speciesHidden;
                                    } else {
                                      return anySelected;
                                    }
                                  }));
                            Curry._1(setCurrentBits, (function (param) {
                                    if (anySelected) {
                                      return ;
                                    } else {
                                      return DataGeneration.BitOps.stringToIntArray(speciesId);
                                    }
                                  }));
                          }));
                  };
                  return React.createElement("div", {
                              className: [" py-1 border rounded-xl mb-2"].join(" ")
                            }, speciesHidden ? React.createElement("div", {
                                    className: ["font-bold"].join(" "),
                                    onClick: onClickHeader
                                  }, speciesNames === "" ? null : React.createElement("div", {
                                          className: "flex flex-row justify-center items-center pb-1"
                                        }, React.createElement("div", {
                                              className: "text-lg flex-none overflow-x-hidden text-ellipsis whitespace-nowrap px-1"
                                            }, speciesNames)), React.createElement("div", {
                                        className: "flex flex-row"
                                      }, React.createElement(App$Scale, {
                                            bitString: speciesId,
                                            currentStepDisplay: currentStepDisplay,
                                            currentKey: currentKey,
                                            kind: /* Species */0,
                                            selected: false
                                          }), React.createElement("div", {
                                            className: " flex-none flex flex-row items-center justify-center w-10 px-1"
                                          }, speciesDetails.isSymmetric ? React.createElement(Bs.BsSymmetryVertical, {}) : null))) : React.createElement("div", undefined, React.createElement("div", {
                                        className: "",
                                        onClick: (function (param) {
                                            Curry._1(setSpeciesHidden, (function (param) {
                                                    return true;
                                                  }));
                                          })
                                      }, React.createElement("div", {
                                            className: "text-lg flex-none font-bold flex flex-row items-center justify-center"
                                          }, speciesNames), React.createElement("div", {
                                            className: "flex flex-row items-center justify-center gap-2"
                                          }, React.createElement("div", {
                                                className: "flex-none"
                                              }, speciesDetails.isSymmetric ? React.createElement(Bs.BsSymmetryVertical, {}) : null), React.createElement("div", {
                                                className: "flex-none text-sm font-medium tracking-wide "
                                              }, "SCALE " + scaleName + ""))), React.createElement("div", {
                                        className: "border-b mx-6 pt-2 border-neutral-500"
                                      }), React.createElement("div", {
                                        className: ["pt-2 pb-1 px-2 flex flex-col divide-y"].join(" ")
                                      }, Belt_Array.mapWithIndex(speciesDetails.modes, (function (_i, param) {
                                              var modeId = param[0];
                                              var selected = Belt_Option.mapWithDefault(currentBits, false, (function (c) {
                                                      return DataGeneration.BitOps.intArrayToString(c) === modeId;
                                                    }));
                                              var modeKind = DataGeneration.startsWith1(DataGeneration.BitOps.stringToStringArray(modeId)) ? /* Mode */1 : /* NonMode */2;
                                              var modeNames = Belt_Option.mapWithDefault(Belt_Array.get(Belt_Array.keepMap(speciesNameData, (function (param) {
                                                                return Belt_Array.getBy(param[2], (function (param) {
                                                                              return modeId === stepsToBits(DataGeneration.BitOps.stringToIntArray(param[0]));
                                                                            }));
                                                              })), 0), [], (function (param) {
                                                        return Belt_Array.map(param[1], (function (param) {
                                                                      return param[1];
                                                                    }));
                                                      })).join(", ");
                                              var tmp;
                                              switch (modeKind) {
                                                case /* Species */0 :
                                                    tmp = "";
                                                    break;
                                                case /* Mode */1 :
                                                    tmp = selected ? "text-accent-600 " : "text-plain-700";
                                                    break;
                                                case /* NonMode */2 :
                                                    tmp = selected ? "bg-plain-50 text-accent-600" : "bg-plain-50 text-plain-300";
                                                    break;
                                                
                                              }
                                              return React.createElement("div", {
                                                          key: modeId,
                                                          className: [
                                                              "flex flex-col py-1 sm:justify-start justify-center ",
                                                              selected ? "font-bold" : "",
                                                              tmp
                                                            ].join(" "),
                                                          onClick: (function (param) {
                                                              Curry._1(setCurrentBits, (function (param) {
                                                                      return DataGeneration.BitOps.stringToIntArray(modeId);
                                                                    }));
                                                            })
                                                        }, modeNames === "" ? null : React.createElement("div", {
                                                                className: "flex flex-row items-center text-xs px-3 justify-center flex-1 overflow-x-hidden text-ellipsis whitespace-nowrap"
                                                              }, modeNames), React.createElement(App$Scale, {
                                                              bitString: modeId,
                                                              currentStepDisplay: currentStepDisplay,
                                                              currentKey: currentKey,
                                                              kind: modeKind,
                                                              selected: selected
                                                            }));
                                            })))));
                })
            });
}

var Species = {
  make: App$Species
};

function App$PageTitle(Props) {
  return React.createElement("div", {
              className: "font-sans  flex flex-row py-2 "
            }, React.createElement(make, {
                  size: 32
                }), React.createElement("div", {
                  className: " -ml-2"
                }, React.createElement("div", {
                      className: " text-[rgb(25,0,175)] font-bold text-3xl"
                    }, "opotonic")));
}

var PageTitle = {
  make: App$PageTitle
};

function App$Card(Props) {
  var title = Props.title;
  var classNameOpt = Props.className;
  var children = Props.children;
  var className = classNameOpt !== undefined ? classNameOpt : "";
  return React.createElement("div", {
              className: [
                  "border  border-neutral-300 rounded-xl mt-2 overflow-hidden ",
                  className
                ].join(" ")
            }, React.createElement("div", {
                  className: "px-6"
                }, React.createElement("div", {
                      className: "w-full text-center py-2 font-bold border-b border-neutral-300 "
                    }, title)), React.createElement("div", {
                  className: "px-2 py-3"
                }, children));
}

var Card = {
  make: App$Card
};

var make$2 = AboutJsx;

var About = {
  make: make$2
};

function generateChromaticScale(startFrequency, numNotes) {
  var semitoneRatio = Math.pow(2, 1 / 12);
  return Belt_Array.map(Belt_Array.range(0, numNotes), (function (v) {
                return startFrequency * Math.pow(semitoneRatio, v) | 0;
              }));
}

function makeNotePlayer(prim) {
  return new NotePlayerJs();
}

var triggerAttackRelease = ToneJs;

function App(Props) {
  var match = React.useState(function () {
        
      });
  var setCurrentBits = match[1];
  var currentBits = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setSelectedGenus = match$1[1];
  var selectedGenus = match$1[0];
  var match$2 = React.useState(function () {
        return 0;
      });
  var setCurrentKey = match$2[1];
  var currentKey = match$2[0];
  var match$3 = React.useState(function () {
        return /* Key */0;
      });
  var setCurrentStepDisplay = match$3[1];
  var currentStepDisplay = match$3[0];
  var graphDisplay;
  switch (currentStepDisplay) {
    case /* Key */0 :
        graphDisplay = DataGeneration.rotate(pitchKeys, currentKey);
        break;
    case /* MinMaj */1 :
        graphDisplay = mMPs;
        break;
    case /* DimAug */2 :
        graphDisplay = dimAugs;
        break;
    case /* Semitone */3 :
    case /* SemitoneSteps */4 :
    case /* HalfnoteSteps */5 :
    case /* Binary */6 :
        graphDisplay = semitones;
        break;
    
  }
  var graphBits = Belt_Option.mapWithDefault(currentBits, Belt_Array.map(Belt_Array.range(0, DataGeneration.Config.bits - 1 | 0), (function (param) {
              return 0;
            })), (function (b) {
          return b;
        }));
  var modeNames = Belt_Option.mapWithDefault(Belt_Array.get(Belt_Array.keepMap(Data.namedSpecies, (function (param) {
                    return Belt_Array.getBy(param[2], (function (param) {
                                  return DataGeneration.BitOps.intArrayToString(graphBits) === stepsToBits(DataGeneration.BitOps.stringToIntArray(param[0]));
                                }));
                  })), 0), [], (function (param) {
            return Belt_Array.map(param[1], (function (param) {
                          return param[1];
                        }));
          })).join(", ");
  var scaleNames = Belt_Array.concatMany(Belt_Array.keepMap(Data.namedSpecies, (function (param) {
                var sId = param[0];
                var isMatch = DataGeneration.any(DataGeneration.getRotations(graphBits), (function (x) {
                        return DataGeneration.BitOps.intArrayToString(x) === stepsToBits(DataGeneration.BitOps.stringToIntArray(sId));
                      }));
                if (isMatch) {
                  return Belt_Array.map(param[1], (function (param) {
                                return param[1];
                              }));
                }
                
              }))).join(", ");
  return React.createElement("div", {
              className: "flex sm:flex-row flex-col h-screen w-screen "
            }, React.createElement("div", {
                  className: "flex-1 flex flex-col w-screen sm:w-auto sm:max-w-[350px] p-2  overflow-y-scroll items-center"
                }, React.createElement("div", {
                      className: "flex flex-row justify-between items-center w-full px-4"
                    }, React.createElement(App$PageTitle, {}), Belt_Option.isNone(currentBits) ? null : React.createElement("button", {
                            className: "flex flex-row gap-2 py-1 px-5 rounded-full items-center\n               justify-center font-bold text-white bg-accent-600   hover:bg-accent-700",
                            onClick: (function (param) {
                                var cChromScale = generateChromaticScale(110, 12);
                                var newBase = Belt_Option.getWithDefault(Belt_Array.get(cChromScale, currentKey), 110);
                                var newChromScale = generateChromaticScale(110 + newBase | 0, 12);
                                var x = Belt_Array.keepWithIndex(newChromScale, (function (_v, i) {
                                        return Belt_Option.mapWithDefault(Belt_Array.get(graphBits, i), false, (function (bit) {
                                                      return bit === 1;
                                                    }));
                                      }));
                                var seq = Belt_Option.mapWithDefault(Belt_Array.get(x, 0), x, (function (head) {
                                        return Belt_Array.concat(x, [(head << 1)]);
                                      }));
                                Belt_Array.forEachWithIndex(seq, (function (i, v) {
                                        triggerAttackRelease(v, "8n", i * 0.5);
                                      }));
                              })
                          }, React.createElement(Fa.FaPlay, {
                                size: 14
                              }), "Play")), React.createElement("div", {
                      className: " sm:max-h-min  max-w-[500px] w-full"
                    }, React.createElement("div", {
                          className: "pt-2 w-full self-center"
                        }, React.createElement(make$1, {
                              data: Belt_Array.zip(graphDisplay, graphBits)
                            })), scaleNames === "" ? null : React.createElement("div", {
                            className: "w-full text-lg text-center mt-4 font-bold text-accent-600"
                          }, "Scale: " + scaleNames + ""), modeNames === "" ? null : React.createElement("div", {
                            className: "w-full text-lg text-center font-bold text-accent-600"
                          }, "Mode: " + modeNames + ""), React.createElement(App$Card, {
                          title: "Key",
                          className: "mt-4",
                          children: React.createElement("div", {
                                className: "grid grid-cols-4 gap-2 w-full "
                              }, Belt_Array.mapWithIndex(pitchKeys, (function (i, v) {
                                      var selected = i === currentKey;
                                      return React.createElement(App$StepButton, {
                                                  selected: selected,
                                                  onClick: (function (param) {
                                                      Curry._1(setCurrentKey, (function (param) {
                                                              return i;
                                                            }));
                                                    }),
                                                  children: v,
                                                  key: v
                                                });
                                    })))
                        }), React.createElement(App$Card, {
                          title: "Step Display",
                          children: null
                        }, React.createElement(App$StepButton, {
                              selected: currentStepDisplay === /* Key */0,
                              onClick: (function (param) {
                                  Curry._1(setCurrentStepDisplay, (function (param) {
                                          return /* Key */0;
                                        }));
                                }),
                              children: "Key"
                            }), React.createElement("div", {
                              className: "grid grid-cols-3 gap-2 w-full pb-2 pt-2"
                            }, React.createElement(App$StepButton, {
                                  selected: currentStepDisplay === /* MinMaj */1,
                                  onClick: (function (param) {
                                      Curry._1(setCurrentStepDisplay, (function (param) {
                                              return /* MinMaj */1;
                                            }));
                                    }),
                                  children: "Min-Maj Int."
                                }), React.createElement(App$StepButton, {
                                  selected: currentStepDisplay === /* DimAug */2,
                                  onClick: (function (param) {
                                      Curry._1(setCurrentStepDisplay, (function (param) {
                                              return /* DimAug */2;
                                            }));
                                    }),
                                  children: "Dim-Aug Int."
                                }), React.createElement(App$StepButton, {
                                  selected: currentStepDisplay === /* Semitone */3,
                                  onClick: (function (param) {
                                      Curry._1(setCurrentStepDisplay, (function (param) {
                                              return /* Semitone */3;
                                            }));
                                    }),
                                  children: "Semitone Int."
                                })), React.createElement("div", {
                              className: "grid grid-cols-2 gap-2 w-full pb-2"
                            }, React.createElement(App$StepButton, {
                                  selected: currentStepDisplay === /* SemitoneSteps */4,
                                  onClick: (function (param) {
                                      Curry._1(setCurrentStepDisplay, (function (param) {
                                              return /* SemitoneSteps */4;
                                            }));
                                    }),
                                  children: "Semitone Steps"
                                }), React.createElement(App$StepButton, {
                                  selected: currentStepDisplay === /* HalfnoteSteps */5,
                                  onClick: (function (param) {
                                      Curry._1(setCurrentStepDisplay, (function (param) {
                                              return /* HalfnoteSteps */5;
                                            }));
                                    }),
                                  children: "Halfnote Steps"
                                })), React.createElement("div", {
                              className: " "
                            }, React.createElement(App$StepButton, {
                                  selected: currentStepDisplay === /* Binary */6,
                                  onClick: (function (param) {
                                      Curry._1(setCurrentStepDisplay, (function (param) {
                                              return /* Binary */6;
                                            }));
                                    }),
                                  children: "Binary"
                                }))))), React.createElement("div", {
                  className: "flex-1 sm:flex-1 h-full overflow-scroll xs:px-2"
                }, React.createElement("div", {
                      className: "sm:max-w-[500px] pt-2"
                    }, React.createElement(App$Collapsed, {
                          render: (function (collapsedState, setCollapsedState) {
                              return React.createElement("div", undefined, React.createElement("button", {
                                              className: "px-3 py-1 my-2 font-bold border border-neutral-300 rounded-lg \n              flex flex-row justify-center items-center gap-1",
                                              onClick: (function (param) {
                                                  Curry._1(setCollapsedState, (function (s) {
                                                          return !s;
                                                        }));
                                                })
                                            }, "About Topotonic", collapsedState ? React.createElement(Fa.FaChevronDown, {}) : React.createElement(Fa.FaChevronUp, {})), React.createElement("div", {
                                              className: [collapsedState ? "hidden" : ""].join(" ")
                                            }, React.createElement(make$2, {})));
                            })
                        }), React.createElement(App$Card, {
                          title: "Number of notes in scale",
                          children: React.createElement("div", {
                                className: "flex flex-row overflow-x-scroll gap-2"
                              }, Belt_Array.map(Belt_Array.range(1, DataGeneration.Config.bits), (function (num) {
                                      return React.createElement(App$StepButton, {
                                                  selected: Belt_Option.mapWithDefault(selectedGenus, false, (function (param) {
                                                          return num === param[0];
                                                        })),
                                                  onClick: (function (param) {
                                                      Curry._1(setSelectedGenus, (function (param) {
                                                              return Belt_Option.flatMap(Belt_Array.get(Belt_MapInt.keysToArray(DataGeneration.result), num), (function (genusId) {
                                                                            return Belt_Option.map(Belt_MapInt.get(DataGeneration.result, genusId), (function (species) {
                                                                                          return [
                                                                                                  genusId,
                                                                                                  species
                                                                                                ];
                                                                                        }));
                                                                          }));
                                                            }));
                                                    }),
                                                  children: String(num)
                                                });
                                    })))
                        }), Belt_Option.mapWithDefault(selectedGenus, null, (function (param) {
                            var species = param[1];
                            var genusId = param[0];
                            return React.createElement("div", {
                                        className: "mb-1"
                                      }, React.createElement("div", {
                                            className: "flex flex-row items-center py-4 font-medium text-lg "
                                          }, "There are " + String(Belt_MapString.toArray(species).length) + " possible scales of " + String(genusId) + " notes"), React.createElement("div", {
                                            className: [""].join(" ")
                                          }, Belt_Array.map(Belt_MapString.toArray(species), (function (param) {
                                                  var speciesId = param[0];
                                                  return React.createElement(App$Species, {
                                                              genusId: genusId,
                                                              currentBits: currentBits,
                                                              currentStepDisplay: currentStepDisplay,
                                                              setCurrentBits: setCurrentBits,
                                                              currentKey: currentKey,
                                                              speciesId: speciesId,
                                                              speciesDetails: param[1],
                                                              key: speciesId
                                                            });
                                                }))));
                          })))));
}

var result = DataGeneration.result;

var BitOps;

var make$3 = App;

var $$default = App;

export {
  result ,
  join ,
  str ,
  reactMap ,
  reactMapWithIndex ,
  BitOps ,
  Logo ,
  SVG ,
  Symmetry ,
  ChevronDown ,
  ChevronUp ,
  PlayIcon ,
  Collapsed ,
  IntervalRefs ,
  stepsToBits ,
  bitsToSemitoneSteps ,
  bitsToHalfnoteSteps ,
  bitToDisplaySymbol ,
  StepButton ,
  Scale ,
  Species ,
  PageTitle ,
  Card ,
  About ,
  generateChromaticScale ,
  makeNotePlayer ,
  triggerAttackRelease ,
  make$3 as make,
  $$default ,
  $$default as default,
}
/* make Not a pure module */
