// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import * as SVGJsx from "./SVG.jsx";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_MapInt from "rescript/lib/es6/belt_MapInt.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";

function join(__x) {
  return __x.join(" ");
}

function any(a, test) {
  return Belt_Array.reduce(a, false, (function (acc, element) {
                if (acc) {
                  return true;
                } else {
                  return Curry._1(test, element);
                }
              }));
}

function App$Collapsed(Props) {
  var render = Props.render;
  var match = React.useState(function () {
        return true;
      });
  return Curry._2(render, match[0], match[1]);
}

var Collapsed = {
  make: App$Collapsed
};

function App$CollapsedTri(Props) {
  var render = Props.render;
  var match = React.useState(function () {
        return /* One */0;
      });
  return Curry._2(render, match[0], match[1]);
}

var CollapsedTri = {
  make: App$CollapsedTri
};

var make = SVGJsx.SVG;

var SVG = {
  make: make
};

var Config = {
  bits: 12
};

var reactMap = Belt_Array.map;

var reactMapWithIndex = Belt_Array.mapWithIndex;

function str(prim) {
  return prim;
}

function padLeft(_s, l, pad) {
  while(true) {
    var s = _s;
    if (s.length >= l) {
      return s;
    }
    _s = pad + s;
    continue ;
  };
}

function stringToArray(x) {
  return Array.from(x);
}

function arrayToString(x) {
  return Belt_Array.reduce(x, "", (function (acc, value) {
                return acc + value;
              }));
}

function stringArrayToIntArray(x) {
  return Belt_Array.map(x, (function (x) {
                return Belt_Option.getWithDefault(Belt_Int.fromString(x), 0);
              }));
}

function stringToIntArray(x) {
  return stringArrayToIntArray(Array.from(x));
}

function intArrayToString(x) {
  return Belt_Array.reduce(x, "", (function (acc, value) {
                return acc + String(value);
              }));
}

function getBitStrings(numOfBits) {
  return Belt_Array.map(Belt_Array.range(0, Math.pow(2, numOfBits) - 1 | 0), (function (x) {
                return padLeft(x.toString(2), numOfBits, "0");
              }));
}

function count1s(bitArray) {
  return Belt_Array.reduce(bitArray, 0, (function (acc, value) {
                if (value === "1") {
                  return acc + 1 | 0;
                } else {
                  return acc;
                }
              }));
}

function groupByCount(bitArrays) {
  return Belt_Array.reduce(bitArrays, undefined, (function (acc, value) {
                var count = count1s(value);
                return Belt_MapInt.update(acc, count, (function (x) {
                              return Belt_Option.mapWithDefault(x, [value], (function (a) {
                                            return Belt_Array.concat(a, [value]);
                                          }));
                            }));
              }));
}

function cycleArray(_x, _shift) {
  while(true) {
    var shift = _shift;
    var x = _x;
    if (shift <= 0) {
      return x;
    }
    _shift = shift - 1 | 0;
    _x = Belt_Array.concat(x.slice(1), [Belt_Array.getExn(x, 0)]);
    continue ;
  };
}

function bitArrayToDec(x) {
  return Belt_Array.reduceWithIndex(Belt_Array.reverse(x), 0, (function (acc, value, i) {
                return Belt_Option.mapWithDefault(Belt_Int.fromString(value), acc, (function (valueInt) {
                              return (valueInt * Math.pow(2, i) | 0) + acc | 0;
                            }));
              }));
}

function getPermutations(x) {
  var unordered = Belt_Array.map(Belt_Array.range(0, x.length - 1 | 0), (function (i) {
          return cycleArray(x, i);
        }));
  Belt_Array.concat([Belt_Array.getExn(unordered, 0)], Belt_Array.reverse(unordered.slice(1)));
  return Belt_Array.concat([Belt_Array.getExn(unordered, 0)], unordered.slice(1));
}

function generateGreatest(x) {
  var permutations = getPermutations(x);
  return Belt_Array.reduce(permutations, Belt_Array.getExn(permutations, 0), (function (acc, value) {
                var valueDecRep = bitArrayToDec(value);
                var accDecRep = bitArrayToDec(acc);
                if (valueDecRep > accDecRep) {
                  return value;
                } else {
                  return acc;
                }
              }));
}

function removeZeroStarts(permutations) {
  return Belt_Array.keep(permutations, (function (x) {
                return Belt_Array.getExn(x, 0) === "1";
              }));
}

function removeDuplicates(permutations) {
  return Belt_Array.map(Belt_MapString.keysToArray(Belt_MapString.fromArray(Belt_Array.map(permutations, (function (x) {
                            return [
                                    arrayToString(x),
                                    ""
                                  ];
                          })))), (function (x) {
                return Array.from(x);
              }));
}

function isSameArray(a, b) {
  return Belt_Array.every(Belt_Array.zip(a, b), (function (param) {
                return param[0] === param[1];
              }));
}

function hasBilateralSymmetry(x) {
  var l = x.length;
  if (l % 2 === 0) {
    var a = x.slice(1, l / 2 | 0);
    var b = Belt_Array.reverse(x.slice((l / 2 | 0) + 1 | 0));
    var c = x.slice(0, l / 2 | 0);
    var d = Belt_Array.reverse(x.slice(l / 2 | 0));
    if (isSameArray(a, b)) {
      return true;
    } else {
      return isSameArray(c, d);
    }
  }
  var a$1 = x.slice(1, (l + 1 | 0) / 2 | 0);
  var b$1 = x.slice((l + 1 | 0) / 2 | 0);
  return isSameArray(a$1, Belt_Array.reverse(b$1));
}

function groupBySpecies(groupedByCount) {
  return Belt_MapInt.map(groupedByCount, (function (x) {
                return Belt_MapString.mapWithKey(Belt_MapString.fromArray(Belt_Array.map(Belt_MapString.keysToArray(Belt_Array.reduce(x, undefined, (function (acc, value) {
                                              var key = arrayToString(generateGreatest(value));
                                              return Belt_MapString.update(acc, key, (function (x) {
                                                            return Belt_Option.mapWithDefault(x, [value], (function (a) {
                                                                          return Belt_Array.concat(a, [value]);
                                                                        }));
                                                          }));
                                            }))), (function (speciesKey) {
                                      return [
                                              speciesKey,
                                              Belt_Array.reverse(removeDuplicates(removeZeroStarts(getPermutations(Array.from(speciesKey)))))
                                            ];
                                    }))), (function (k, a) {
                              var match = Belt_Array.get(a, 0);
                              var match$1 = Belt_Array.get(a, 1);
                              if (match !== undefined) {
                                if (match$1 !== undefined) {
                                  Belt_Array.keep(Belt_Array.zip(match, match$1), (function (param) {
                                          if (param[0] === "1") {
                                            return param[1] === "1";
                                          } else {
                                            return false;
                                          }
                                        })).length;
                                }
                                
                              }
                              var permutations = getPermutations(Array.from(k));
                              return {
                                      modes: a,
                                      numOfModes: a.length,
                                      autoCorrelations: Belt_Option.mapWithDefault(Belt_Array.get(a, 0), [], (function (match) {
                                              return Belt_Array.map(permutations, (function (p) {
                                                            if (arrayToString(p) === arrayToString(match)) {
                                                              return "_";
                                                            } else {
                                                              return String(Belt_Array.keep(Belt_Array.zip(p, match), (function (param) {
                                                                                if (param[0] === "1") {
                                                                                  return param[1] === "1";
                                                                                } else {
                                                                                  return false;
                                                                                }
                                                                              })).length);
                                                            }
                                                          }));
                                            })),
                                      isSymmetric: any(permutations, hasBilateralSymmetry)
                                    };
                            }));
              }));
}

var result = groupBySpecies(groupByCount(Belt_Array.map(getBitStrings(12), stringToArray)));

var keys = [
  "C",
  "C♯/D♭",
  "D",
  "D♯/E♭",
  "E",
  "F",
  "F♯/G♭",
  "G",
  "G♯/A♭",
  "A",
  "A♯/B♭",
  "B"
];

var keysShort = [
  "C",
  "C♯",
  "D",
  "D♯",
  "E",
  "F",
  "F♯",
  "G",
  "G♯",
  "A",
  "A♯",
  "B"
];

var namedSpecies = [
  [
    "110101101010",
    ["Diatonic"],
    [
      [
        "Locrian",
        "7"
      ],
      [
        "Ionian",
        "1"
      ],
      [
        "Dorian",
        "2"
      ],
      [
        "Phrygian",
        "3"
      ],
      [
        "Lydian",
        "4"
      ],
      [
        "Mixolydian",
        "5"
      ],
      [
        "Aeolian",
        "6"
      ]
    ]
  ],
  [
    "110110011010",
    ["Harmonic Major"],
    []
  ],
  [
    "110101100110",
    ["Harmonic Minor"],
    []
  ],
  [
    "",
    [""],
    []
  ],
  [
    "",
    [""],
    []
  ],
  [
    "",
    [""],
    []
  ],
  [
    "",
    [""],
    []
  ]
];

function spacedToBits(a) {
  return Belt_Array.reduce(a, "1", (function (acc, value) {
                var tmp;
                switch (value) {
                  case 1 :
                      tmp = "1";
                      break;
                  case 2 :
                      tmp = "10";
                      break;
                  case 3 :
                      tmp = "100";
                      break;
                  case 4 :
                      tmp = "1000";
                      break;
                  default:
                    tmp = "";
                }
                return acc + tmp;
              }));
}

function App$Scale(Props) {
  var onClick = Props.onClick;
  var bitString = Props.bitString;
  var currentKey = Props.currentKey;
  var kind = Props.kind;
  var selected = Props.selected;
  return React.createElement("div", {
              className: [
                  " flex flex-row ",
                  kind ? (
                      selected ? "bg-blue-300" : ""
                    ) : "font-bold"
                ].join(" "),
              onClick: onClick
            }, Belt_Array.mapWithIndex(Array.from(bitString), (function (i, bit) {
                    return React.createElement("div", {
                                className: [
                                    (Belt_Option.isSome(currentKey), "w-5"),
                                    "flex flex-row justify-center"
                                  ].join(" ")
                              }, Belt_Option.mapWithDefault(currentKey, bit, (function (shift) {
                                      if (bit === "0") {
                                        return "-";
                                      } else {
                                        return Belt_Option.getWithDefault(Belt_Array.get(cycleArray(keysShort, shift), i), "");
                                      }
                                    })));
                  })));
}

var Scale = {
  make: App$Scale
};

function App$Key(Props) {
  var selected = Props.selected;
  var onClick = Props.onClick;
  var children = Props.children;
  return React.createElement("div", {
              className: [
                  selected ? "bg-blue-300" : "",
                  "rounded p-1 pl-2"
                ].join(" "),
              onClick: onClick
            }, children);
}

var Key = {
  make: App$Key
};

function App$Species(Props) {
  var modes = Props.modes;
  var currentBits = Props.currentBits;
  var setCurrentBits = Props.setCurrentBits;
  var speciesId = Props.speciesId;
  var currentKey = Props.currentKey;
  var isSymmetric = Props.isSymmetric;
  var numOfModes = Props.numOfModes;
  var autoCorrelations = Props.autoCorrelations;
  var match = React.useState(function () {
        
      });
  var setBase = match[1];
  var base = match[0];
  return React.createElement(App$Collapsed, {
              render: (function (speciesHidden, setSpeciesHidden) {
                  var anySelected = any(modes, (function (mode) {
                          return Belt_Option.mapWithDefault(currentBits, false, (function (c) {
                                        return intArrayToString(c) === arrayToString(mode);
                                      }));
                        }));
                  return React.createElement("div", {
                              className: [
                                  speciesHidden ? "border-transparent" : "bg-blue-50 border-blue-200 mb-1",
                                  "border rounded-sm"
                                ].join(" ")
                            }, React.createElement("div", {
                                  className: "flex flex-row items-center justify-start gap-3"
                                }, React.createElement(App$Scale, {
                                      onClick: (function (param) {
                                          Belt_Option.mapWithDefault(currentBits, (Curry._1(setSpeciesHidden, (function (param) {
                                                        return false;
                                                      })), Curry._1(setCurrentBits, (function (param) {
                                                        return stringArrayToIntArray(Array.from(speciesId));
                                                      }))), (function (param) {
                                                  Curry._1(setSpeciesHidden, (function (param) {
                                                          if (speciesHidden) {
                                                            return !speciesHidden;
                                                          } else {
                                                            return anySelected;
                                                          }
                                                        }));
                                                  Curry._1(setCurrentBits, (function (param) {
                                                          if (anySelected) {
                                                            return ;
                                                          } else {
                                                            return stringArrayToIntArray(Array.from(speciesId));
                                                          }
                                                        }));
                                                }));
                                        }),
                                      bitString: speciesId,
                                      currentKey: currentKey,
                                      kind: /* Species */0,
                                      selected: false
                                    }), React.createElement("div", {
                                      className: "w-6"
                                    }, isSymmetric ? "x" : ""), React.createElement("div", {
                                      className: "text-sm whitespace-nowrap"
                                    }, String(numOfModes), " modes")), React.createElement("div", {
                                  className: [
                                      speciesHidden ? "hidden " : "",
                                      "pt-0.5 pb-2 border-t border-neutral-400"
                                    ].join(" ")
                                }, Belt_Array.map(modes, (function (modeId) {
                                        var selected = Belt_Option.mapWithDefault(currentBits, false, (function (c) {
                                                return intArrayToString(c) === arrayToString(modeId);
                                              }));
                                        return React.createElement("div", {
                                                    className: "flex flex-row"
                                                  }, React.createElement(App$Scale, {
                                                        onClick: (function (param) {
                                                            Curry._1(setCurrentBits, (function (param) {
                                                                    return stringArrayToIntArray(modeId);
                                                                  }));
                                                          }),
                                                        bitString: arrayToString(modeId),
                                                        currentKey: currentKey,
                                                        kind: /* Mode */1,
                                                        selected: selected
                                                      }), Belt_Option.isSome(currentKey) ? Belt_Option.mapWithDefault(base, React.createElement("button", {
                                                              onClick: (function (param) {
                                                                  Curry._1(setBase, (function (param) {
                                                                          return modeId;
                                                                        }));
                                                                })
                                                            }, "Base"), (function (b) {
                                                            if (arrayToString(b) === arrayToString(modeId)) {
                                                              return React.createElement("button", {
                                                                          onClick: (function (param) {
                                                                              Curry._1(setBase, (function (param) {
                                                                                      
                                                                                    }));
                                                                            })
                                                                        }, "Remove");
                                                            } else {
                                                              return null;
                                                            }
                                                          })) : null);
                                      })), React.createElement("div", {
                                      className: "text-xs text-green-600 flex flex-row "
                                    }, Belt_Array.map(autoCorrelations, (function (x) {
                                            return React.createElement("div", {
                                                        className: ["w-5 flex flex-row items-center justify-center"].join(" ")
                                                      }, x);
                                          })))));
                })
            });
}

var Species = {
  make: App$Species
};

function App(Props) {
  var match = React.useState(function () {
        
      });
  var setCurrentBits = match[1];
  var currentBits = match[0];
  var match$1 = React.useState(function () {
        
      });
  var setCurrentKey = match$1[1];
  var currentKey = match$1[0];
  var graphKeys = Belt_Option.mapWithDefault(currentKey, Belt_Array.mapWithIndex(keys, (function (i, param) {
              return String(i);
            })), (function (shift) {
          return cycleArray(keys, shift);
        }));
  var graphBits = Belt_Option.mapWithDefault(currentBits, Belt_Array.map(keys, (function (param) {
              return 0;
            })), (function (b) {
          return b;
        }));
  return React.createElement("div", {
              className: "flex flex-row h-screen w-screen font-mono"
            }, React.createElement("div", {
                  className: " h-full flex flex-col p-4"
                }, React.createElement("div", {
                      className: "h-80 w-80"
                    }, React.createElement(make, {
                          data: Belt_Array.zip(graphKeys, graphBits)
                        })), React.createElement("div", {
                      className: "flex-1 overflow-scroll p-1 border rounded"
                    }, React.createElement(App$Key, {
                          selected: Belt_Option.isNone(currentKey),
                          onClick: (function (param) {
                              Curry._1(setCurrentKey, (function (param) {
                                      
                                    }));
                            }),
                          children: "None"
                        }), Belt_Array.mapWithIndex(keys, (function (i, v) {
                            var selected = Belt_Option.mapWithDefault(currentKey, false, (function (c) {
                                    return c === i;
                                  }));
                            return React.createElement(App$Key, {
                                        selected: selected,
                                        onClick: (function (param) {
                                            Curry._1(setCurrentKey, (function (param) {
                                                    return i;
                                                  }));
                                          }),
                                        children: v
                                      });
                          })))), React.createElement("div", {
                  className: "flex-1 h-full overflow-scroll pr-4"
                }, Belt_Array.map(Belt_MapInt.toArray(result), (function (param) {
                        var species = param[1];
                        var genusId = param[0];
                        return React.createElement(App$CollapsedTri, {
                                    render: (function (genusCollapsedState, setGenusCollapsedState) {
                                        var tmp;
                                        switch (genusCollapsedState) {
                                          case /* One */0 :
                                              tmp = "hidden";
                                              break;
                                          case /* Two */1 :
                                              tmp = "max-h-64";
                                              break;
                                          case /* Three */2 :
                                              tmp = "";
                                              break;
                                          
                                        }
                                        return React.createElement("div", {
                                                    className: "mb-1"
                                                  }, React.createElement("div", {
                                                        className: "flex flex-row items-center px-4 ",
                                                        onClick: (function (param) {
                                                            Curry._1(setGenusCollapsedState, (function (s) {
                                                                    switch (s) {
                                                                      case /* One */0 :
                                                                          return /* Two */1;
                                                                      case /* Two */1 :
                                                                          return /* Three */2;
                                                                      case /* Three */2 :
                                                                          return /* One */0;
                                                                      
                                                                    }
                                                                  }));
                                                          })
                                                      }, React.createElement("div", {
                                                            className: "flex-1 text-lg"
                                                          }, String(genusId)), React.createElement("div", {
                                                            className: "flex-1 text-sm whitespace-nowrap"
                                                          }, String(Belt_MapString.toArray(species).length), " species")), React.createElement("div", {
                                                        className: [
                                                            tmp,
                                                            "overflow-scroll p-2 pb-6 border"
                                                          ].join(" ")
                                                      }, Belt_Array.map(Belt_Array.reverse(Belt_MapString.toArray(species)), (function (param) {
                                                              var match = param[1];
                                                              return React.createElement(App$Species, {
                                                                          modes: match.modes,
                                                                          currentBits: currentBits,
                                                                          setCurrentBits: setCurrentBits,
                                                                          speciesId: param[0],
                                                                          currentKey: currentKey,
                                                                          isSymmetric: match.isSymmetric,
                                                                          numOfModes: match.numOfModes,
                                                                          autoCorrelations: match.autoCorrelations
                                                                        });
                                                            }))));
                                      })
                                  });
                      }))));
}

var make$1 = App;

var $$default = App;

export {
  join ,
  any ,
  Collapsed ,
  CollapsedTri ,
  SVG ,
  Config ,
  reactMap ,
  reactMapWithIndex ,
  str ,
  padLeft ,
  stringToArray ,
  arrayToString ,
  stringArrayToIntArray ,
  stringToIntArray ,
  intArrayToString ,
  getBitStrings ,
  count1s ,
  groupByCount ,
  cycleArray ,
  bitArrayToDec ,
  getPermutations ,
  generateGreatest ,
  removeZeroStarts ,
  removeDuplicates ,
  isSameArray ,
  hasBilateralSymmetry ,
  groupBySpecies ,
  result ,
  keys ,
  keysShort ,
  namedSpecies ,
  spacedToBits ,
  Scale ,
  Key ,
  Species ,
  make$1 as make,
  $$default ,
  $$default as default,
}
/* make Not a pure module */
