// Generated by ReScript, PLEASE EDIT WITH CARE


var namedSpecies = [
  [
    "255",
    [],
    [
      [
        0,
        [[
            /* Misc */0,
            "Suspended second"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Suspended fourth"
          ]]
      ]
    ]
  ],
  [
    "435",
    [[
        /* Misc */0,
        "Major triad"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Major triad, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Major triad, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Major triad, 2nd inversion"
          ]]
      ]
    ]
  ],
  [
    "4323",
    [
      [
        /* Misc */0,
        "Major sixth"
      ],
      [
        /* Misc */0,
        "Minor seventh"
      ]
    ],
    [
      [
        0,
        [[
            /* Misc */0,
            "Major sixth, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Major sixth, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Major sixth, 2nd inversion"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Minor seventh"
          ]]
      ]
    ]
  ],
  [
    "4332",
    [[
        /* Misc */0,
        "Dominant seventh"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Dominant seventh, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Dominant seventh, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Dominant seventh, 2nd inversion"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Dominant seventh, 3rd inversion"
          ]]
      ]
    ]
  ],
  [
    "4341",
    [[
        /* Misc */0,
        "Major seventh"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Major seventh, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Major seventh, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Major seventh, 2nd inversion"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Major seventh, 3rd inversion"
          ]]
      ]
    ]
  ],
  [
    "444",
    [[
        /* Misc */0,
        "Augmented triad"
      ]],
    []
  ],
  [
    "4422",
    [[
        /* Misc */0,
        "Augmented seventh"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Augmented seventh, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Augmented seventh, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Augmented seventh, 2nd inversion"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Augmented seventh, 3rd inversion"
          ]]
      ]
    ]
  ],
  [
    "345",
    [[
        /* Misc */0,
        "Minor triad"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Minor triad, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Minor triad, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Minor triad, 2nd inversion"
          ]]
      ]
    ]
  ],
  [
    "3423",
    [
      [
        /* Misc */0,
        "Minor sixth"
      ],
      [
        /* Misc */0,
        "Half-diminished seventh"
      ]
    ],
    [
      [
        0,
        [[
            /* Misc */0,
            "Minor sixth, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Minor sixth, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Minor sixth, 2nd inversion"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Half-diminished seventh"
          ]]
      ]
    ]
  ],
  [
    "3441",
    [[
        /* Misc */0,
        "Minor-major seventh"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Minor-major seventh, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Minor-major seventh, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Minor-major seventh, 2nd inversion"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Minor-major seventh, 3rd inversion"
          ]]
      ]
    ]
  ],
  [
    "336",
    [[
        /* Misc */0,
        "Diminished triad"
      ]],
    [
      [
        0,
        [[
            /* Misc */0,
            "Diminished triad, root position"
          ]]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Diminished triad, 1st inversion"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Diminished triad, 2nd inversion"
          ]]
      ]
    ]
  ],
  [
    "3333",
    [[
        /* Misc */0,
        "Diminished seventh"
      ]],
    []
  ],
  [
    "22332",
    [[
        /* Misc */0,
        "Dominant ninth"
      ]],
    [[
        0,
        [[
            /* Misc */0,
            "Dominant ninth, root position"
          ]]
      ]]
  ],
  [
    "221232",
    [[
        /* Misc */0,
        "Dominant eleventh"
      ]],
    [[
        0,
        [[
            /* Misc */0,
            "Dominant eleventh, root position"
          ]]
      ]]
  ],
  [
    "22323",
    [[
        /* Misc */0,
        "Pentatonic"
      ]],
    [
      [
        0,
        [
          [
            /* Misc */0,
            "Major Pentatonic"
          ],
          [
            /* ChinesePenta */1,
            "宮 Gong"
          ],
          [
            /* MiddleEast */5,
            "Ajam"
          ]
        ]
      ],
      [
        1,
        [
          [
            /* Misc */0,
            "Egyptian"
          ],
          [
            /* Misc */0,
            "Suspended Pentatonic"
          ],
          [
            /* Misc */0,
            "Jazz sus"
          ],
          [
            /* ChinesePenta */1,
            "商 Shang"
          ]
        ]
      ],
      [
        2,
        [
          [
            /* Misc */0,
            "Blues 5 Minor"
          ],
          [
            /* ChinesePenta */1,
            "角 Jue"
          ]
        ]
      ],
      [
        3,
        [
          [
            /* Misc */0,
            "Ritsusen"
          ],
          [
            /* Misc */0,
            "Yo"
          ],
          [
            /* Misc */0,
            "Blues 5 Major"
          ],
          [
            /* ChinesePenta */1,
            "徵 Zhi"
          ]
        ]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Minor Pentatonic"
          ],
          [
            /* ChinesePenta */1,
            "羽 Yu"
          ]
        ]
      ]
    ]
  ],
  [
    "1221222",
    [[
        /* Misc */0,
        "Diatonic"
      ]],
    [
      [
        0,
        [
          [
            /* Numbers */2,
            "7"
          ],
          [
            /* ModernGreek */3,
            "Locrian"
          ]
        ]
      ],
      [
        1,
        [
          [
            /* Numbers */2,
            "1"
          ],
          [
            /* ModernGreek */3,
            "Ionian"
          ],
          [
            /* Misc */0,
            "Natural Major"
          ]
        ]
      ],
      [
        2,
        [
          [
            /* Numbers */2,
            "2"
          ],
          [
            /* ModernGreek */3,
            "Dorian"
          ]
        ]
      ],
      [
        3,
        [
          [
            /* Numbers */2,
            "3"
          ],
          [
            /* ModernGreek */3,
            "Phrygian"
          ]
        ]
      ],
      [
        4,
        [
          [
            /* Numbers */2,
            "4"
          ],
          [
            /* ModernGreek */3,
            "Lydian"
          ]
        ]
      ],
      [
        5,
        [
          [
            /* Numbers */2,
            "5"
          ],
          [
            /* ModernGreek */3,
            "Mixolydian"
          ],
          [
            /* Misc */0,
            "Dominant thirteenth"
          ],
          [
            /* Jewish */4,
            "Adonai Malakh"
          ]
        ]
      ],
      [
        6,
        [
          [
            /* Numbers */2,
            "6"
          ],
          [
            /* ModernGreek */3,
            "Aeolian"
          ],
          [
            /* Misc */0,
            "Natural Minor"
          ],
          [
            /* Jewish */4,
            "Magein Avot"
          ]
        ]
      ]
    ]
  ],
  [
    "1212222",
    [
      [
        /* Misc */0,
        "Jazz Minor"
      ],
      [
        /* Misc */0,
        "Ascending Melodic Minor"
      ]
    ],
    [
      [
        0,
        [
          [
            /* Misc */0,
            "Altered"
          ],
          [
            /* Misc */0,
            "Altered Dominant"
          ],
          [
            /* Misc */0,
            "Super Locrian"
          ],
          [
            /* Misc */0,
            "Jazz Minor VII"
          ]
        ]
      ],
      [
        1,
        [[
            /* Misc */0,
            "Jazz Minor I"
          ]]
      ],
      [
        2,
        [
          [
            /* Misc */0,
            "Dorian ♭2"
          ],
          [
            /* Misc */0,
            "Phrygian ♮6"
          ],
          [
            /* Misc */0,
            "Jazz Minor II"
          ]
        ]
      ],
      [
        3,
        [
          [
            /* Misc */0,
            "Lydian Augmented"
          ],
          [
            /* Misc */0,
            "Jazz Minor III"
          ]
        ]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Acoustic"
          ],
          [
            /* Misc */0,
            "Lydian Dominant"
          ],
          [
            /* Misc */0,
            "Mixolydian ♯4"
          ],
          [
            /* Misc */0,
            "Overtone"
          ],
          [
            /* Misc */0,
            "Jazz Minor IV"
          ]
        ]
      ],
      [
        5,
        [
          [
            /* Misc */0,
            "Aeolian Dominant"
          ],
          [
            /* Misc */0,
            "Mixolydian ♭6"
          ],
          [
            /* Misc */0,
            "Descending Melodic Major"
          ],
          [
            /* Misc */0,
            "Hindu"
          ],
          [
            /* Misc */0,
            "Jazz Minor V"
          ]
        ]
      ],
      [
        6,
        [
          [
            /* Misc */0,
            "Half-diminished"
          ],
          [
            /* Misc */0,
            "Locrian ♮2"
          ],
          [
            /* Misc */0,
            "Aeolian ♭5"
          ],
          [
            /* Misc */0,
            "Jazz Minor VI"
          ]
        ]
      ]
    ]
  ],
  [
    "14142",
    [],
    [
      [
        0,
        [[
            /* Misc */0,
            "Iwato"
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Hirajoshi"
          ]]
      ]
    ]
  ],
  [
    "14232",
    [],
    [[
        0,
        [[
            /* Misc */0,
            "Insen"
          ]]
      ]]
  ],
  [
    "113232",
    [],
    [[
        4,
        [[
            /* Misc */0,
            "Blues 6"
          ]]
      ]]
  ],
  [
    "222222",
    [[
        /* Misc */0,
        "Whole Tone"
      ]],
    []
  ],
  [
    "131313",
    [],
    [[
        1,
        [[
            /* Misc */0,
            "Augmented"
          ]]
      ]]
  ],
  [
    "121215",
    [],
    [[
        0,
        [[
            /* Misc */0,
            "Istrian"
          ]]
      ]]
  ],
  [
    "122223",
    [],
    [[
        2,
        [[
            /* Misc */0,
            "Prometheus"
          ]]
      ]]
  ],
  [
    "132132",
    [[
        /* Misc */0,
        "Tritone"
      ]],
    []
  ],
  [
    "1132212",
    [],
    [[
        4,
        [[
            /* Misc */0,
            "Blues 7"
          ]]
      ]]
  ],
  [
    "1212132",
    [],
    [[
        5,
        [[
            /* Misc */0,
            "Romanian Major"
          ]]
      ]]
  ],
  [
    "1213122",
    [[
        /* Misc */0,
        "Harmonic Major"
      ]],
    [[
        5,
        [[
            /* Misc */0,
            "Harmonic Major I"
          ]]
      ]]
  ],
  [
    "2121222",
    [],
    [[
        0,
        [[
            /* Jewish */4,
            "Yistabach"
          ]]
      ]]
  ],
  [
    "1212213",
    [[
        /* Misc */0,
        "Harmonic Minor"
      ]],
    [
      [
        1,
        [[
            /* Misc */0,
            "Harmonic Minor I"
          ]]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Ukranian Dorian"
          ],
          [
            /* Jewish */4,
            "Mi Sheberach"
          ]
        ]
      ],
      [
        5,
        [
          [
            /* Misc */0,
            "Phrygian Dominant"
          ],
          [
            /* Jewish */4,
            "Ahavah Rabbah"
          ],
          [
            /* MiddleEast */5,
            "Hijaz"
          ]
        ]
      ]
    ]
  ],
  [
    "1131213",
    [[
        /* Misc */0,
        "Double Harmonic"
      ]],
    [
      [
        1,
        [
          [
            /* Misc */0,
            "Double Harmonic Major"
          ],
          [
            /* Misc */0,
            "Gypsy Major"
          ],
          [
            /* Misc */0,
            "Byzantine"
          ],
          [
            /* Misc */0,
            "Arabic (Hijaz Kar)"
          ],
          [
            /* Misc */0,
            "Bhairav Raga"
          ],
          [
            /* Misc */0,
            "Mayamalavagowla"
          ]
        ]
      ],
      [
        2,
        [[
            /* Misc */0,
            ""
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Ultraphrygian"
          ]]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Double Harmonic Minor"
          ],
          [
            /* Misc */0,
            "Hungarian Minor"
          ],
          [
            /* Misc */0,
            "Gypsy Minor"
          ],
          [
            /* Misc */0,
            "Algerian (First Octave)"
          ],
          [
            /* MiddleEast */5,
            "Nawa Athar"
          ]
        ]
      ],
      [
        5,
        [[
            /* Misc */0,
            "Oriental"
          ]]
      ],
      [
        6,
        [[
            /* Misc */0,
            ""
          ]]
      ],
      [
        0,
        [[
            /* Misc */0,
            ""
          ]]
      ]
    ]
  ],
  [
    "1212123",
    [],
    [[
        6,
        [[
            /* Misc */0,
            "Hungarian Major"
          ]]
      ]]
  ],
  [
    "1113222",
    [],
    [[
        2,
        [[
            /* Misc */0,
            "Enigmatic"
          ]]
      ]]
  ],
  [
    "1122213",
    [],
    [
      [
        1,
        [[
            /* Misc */0,
            "Neapolitan Minor"
          ]]
      ],
      [
        4,
        [[
            /* Misc */0,
            "Gypsy Minor"
          ]]
      ],
      [
        0,
        [[
            /* Misc */0,
            "Ultralocrian"
          ]]
      ]
    ]
  ],
  [
    "1122222",
    [],
    [
      [
        1,
        [[
            /* Misc */0,
            "Neapolitan Major"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Leading Whole Tone"
          ]]
      ],
      [
        6,
        [[
            /* Misc */0,
            "Major Locrian"
          ]]
      ]
    ]
  ],
  [
    "1123113",
    [],
    [[
        5,
        [[
            /* Misc */0,
            "Persian"
          ]]
      ]]
  ],
  [
    "12121212",
    [[
        /* Misc */0,
        "Octatonic"
      ]],
    []
  ],
  [
    "11122122",
    [],
    [[
        3,
        [[
            /* Misc */0,
            "Bebop Dominant"
          ]]
      ]]
  ],
  [
    "11212212",
    [],
    [
      [
        2,
        [[
            /* Misc */0,
            "Bebop Harmonic Minor"
          ]]
      ],
      [
        4,
        [[
            /* Misc */0,
            "Bebop Major"
          ]]
      ]
    ]
  ],
  [
    "11212122",
    [],
    [[
        4,
        [[
            /* Misc */0,
            "Bebop Melodic Minor"
          ]]
      ]]
  ],
  [
    "11221122",
    [],
    [[
        2,
        [[
            /* Misc */0,
            "Seventh flat 5 diminished"
          ]]
      ]]
  ],
  [
    "111112122",
    [
      [
        /* Misc */0,
        "Melodic Minor"
      ],
      [
        /* MiddleEast */5,
        "Nahawand"
      ]
    ],
    []
  ],
  [
    "111211122",
    [],
    [[
        3,
        [[
            /* Misc */0,
            "Blues 9"
          ]]
      ]]
  ],
  [
    "111111111111",
    [[
        /* Misc */0,
        "Chromatic"
      ]],
    []
  ]
];

export {
  namedSpecies ,
}
/* No side effect */
