// Generated by ReScript, PLEASE EDIT WITH CARE


var namedSpecies = [
  [
    "22323",
    [[
        /* Misc */0,
        "Pentatonic"
      ]],
    [
      [
        0,
        [
          [
            /* Misc */0,
            "Major Pentatonic"
          ],
          [
            /* ChinesePenta */1,
            "宮 Gong"
          ],
          [
            /* MiddleEast */5,
            "Ajam"
          ]
        ]
      ],
      [
        1,
        [
          [
            /* Misc */0,
            "Egyptian"
          ],
          [
            /* Misc */0,
            "Suspended Pentatonic"
          ],
          [
            /* ChinesePenta */1,
            "商 Shang"
          ]
        ]
      ],
      [
        2,
        [
          [
            /* Misc */0,
            "Blues 5 Minor"
          ],
          [
            /* ChinesePenta */1,
            "角 Jue"
          ]
        ]
      ],
      [
        3,
        [
          [
            /* Misc */0,
            "Ritsusen"
          ],
          [
            /* Misc */0,
            "Yo"
          ],
          [
            /* Misc */0,
            "Blues 5 Major"
          ],
          [
            /* ChinesePenta */1,
            "徵 Zhi"
          ]
        ]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Minor Pentatonic"
          ],
          [
            /* ChinesePenta */1,
            "羽 Yu"
          ]
        ]
      ]
    ]
  ],
  [
    "1221222",
    [[
        /* Misc */0,
        "Diatonic"
      ]],
    [
      [
        0,
        [
          [
            /* Numbers */2,
            "7"
          ],
          [
            /* ModernGreek */3,
            "Locrian"
          ]
        ]
      ],
      [
        1,
        [
          [
            /* Numbers */2,
            "1"
          ],
          [
            /* ModernGreek */3,
            "Ionian"
          ],
          [
            /* Misc */0,
            "Natural Major"
          ]
        ]
      ],
      [
        2,
        [
          [
            /* Numbers */2,
            "2"
          ],
          [
            /* ModernGreek */3,
            "Dorian"
          ]
        ]
      ],
      [
        3,
        [
          [
            /* Numbers */2,
            "3"
          ],
          [
            /* ModernGreek */3,
            "Phrygian"
          ]
        ]
      ],
      [
        4,
        [
          [
            /* Numbers */2,
            "4"
          ],
          [
            /* ModernGreek */3,
            "Lydian"
          ]
        ]
      ],
      [
        5,
        [
          [
            /* Numbers */2,
            "5"
          ],
          [
            /* ModernGreek */3,
            "Mixolydian"
          ],
          [
            /* Jewish */4,
            "Adonai Malakh"
          ]
        ]
      ],
      [
        6,
        [
          [
            /* Numbers */2,
            "6"
          ],
          [
            /* ModernGreek */3,
            "Aeolian"
          ],
          [
            /* Misc */0,
            "Natural Minor"
          ],
          [
            /* Jewish */4,
            "Magein Avot"
          ]
        ]
      ]
    ]
  ],
  [
    "1212222",
    [
      [
        /* Misc */0,
        "Melodic"
      ],
      [
        /* Misc */0,
        "Half Diminished"
      ]
    ],
    [[
        0,
        [
          [
            /* Misc */0,
            "Altered"
          ],
          [
            /* Misc */0,
            "Palamidian"
          ],
          [
            /* Misc */0,
            "Super Locrian"
          ]
        ]
      ]]
  ],
  [
    "21414",
    [[
        /* Misc */0,
        "Hirajoshi"
      ]],
    []
  ],
  [
    "14232",
    [[
        /* Misc */0,
        "Insen"
      ]],
    []
  ],
  [
    "14142",
    [[
        /* Misc */0,
        "Iwato"
      ]],
    []
  ],
  [
    "321132",
    [[
        /* Misc */0,
        "Blues 6"
      ]],
    []
  ],
  [
    "222222",
    [[
        /* Misc */0,
        "Whole Tone"
      ]],
    []
  ],
  [
    "222123",
    [[
        /* Misc */0,
        "Acoustic"
      ]],
    []
  ],
  [
    "313131",
    [[
        /* Misc */0,
        "Augmented"
      ]],
    []
  ],
  [
    "121215",
    [[
        /* Misc */0,
        "Istrian"
      ]],
    []
  ],
  [
    "222312",
    [[
        /* Misc */0,
        "Prometheus"
      ]],
    []
  ],
  [
    "132132",
    [[
        /* Misc */0,
        "Tritone"
      ]],
    []
  ],
  [
    "2121132",
    [[
        /* Misc */0,
        "Blues 7"
      ]],
    []
  ],
  [
    "1212132",
    [],
    [[
        5,
        [[
            /* Misc */0,
            "Romanian Major"
          ]]
      ]]
  ],
  [
    "2212131",
    [[
        /* Misc */0,
        "Harmonic Major"
      ]],
    []
  ],
  [
    "2121222",
    [],
    [[
        0,
        [[
            /* Jewish */4,
            "Yistabach"
          ]]
      ]]
  ],
  [
    "1212213",
    [[
        /* Misc */0,
        "Harmonic Minor"
      ]],
    [
      [
        1,
        [[
            /* Misc */0,
            "Harmonic Minor I"
          ]]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Ukranian Dorian"
          ],
          [
            /* Jewish */4,
            "Mi Sheberach"
          ]
        ]
      ],
      [
        5,
        [
          [
            /* Misc */0,
            "Phrygian Dominant"
          ],
          [
            /* Jewish */4,
            "Ahavah Rabbah"
          ],
          [
            /* MiddleEast */5,
            "Hijaz"
          ]
        ]
      ]
    ]
  ],
  [
    "1131213",
    [[
        /* Misc */0,
        "Double Harmonic"
      ]],
    [
      [
        1,
        [
          [
            /* Misc */0,
            "Double Harmonic Major"
          ],
          [
            /* Misc */0,
            "Gypsy Major"
          ]
        ]
      ],
      [
        2,
        [[
            /* Misc */0,
            ""
          ]]
      ],
      [
        3,
        [[
            /* Misc */0,
            "Ultraphrygian"
          ]]
      ],
      [
        4,
        [
          [
            /* Misc */0,
            "Double Harmonic Minor"
          ],
          [
            /* Misc */0,
            "Hungarian Minor"
          ],
          [
            /* Misc */0,
            "Gypsy Minor"
          ],
          [
            /* Misc */0,
            "Algerian"
          ],
          [
            /* MiddleEast */5,
            "Nawa Athar"
          ]
        ]
      ],
      [
        5,
        [[
            /* Misc */0,
            "Oriental"
          ]]
      ],
      [
        6,
        [[
            /* Misc */0,
            ""
          ]]
      ],
      [
        0,
        [[
            /* Misc */0,
            ""
          ]]
      ]
    ]
  ],
  [
    "1113222",
    [],
    [[
        2,
        [[
            /* Misc */0,
            "Enigmatic"
          ]]
      ]]
  ],
  [
    "1122213",
    [],
    [
      [
        1,
        [[
            /* Misc */0,
            "Neapolitan Minor"
          ]]
      ],
      [
        4,
        [[
            /* Misc */0,
            "Gypsy Minor"
          ]]
      ],
      [
        0,
        [[
            /* Misc */0,
            "Ultralocrian"
          ]]
      ]
    ]
  ],
  [
    "1122222",
    [],
    [
      [
        1,
        [[
            /* Misc */0,
            "Neapolitan Major"
          ]]
      ],
      [
        2,
        [[
            /* Misc */0,
            "Leading Whole Tone"
          ]]
      ],
      [
        6,
        [[
            /* Misc */0,
            "Major Locrian"
          ]]
      ]
    ]
  ],
  [
    "1123113",
    [],
    [[
        5,
        [[
            /* Misc */0,
            "Persian"
          ]]
      ]]
  ],
  [
    "12121212",
    [[
        /* Misc */0,
        "Octatonic"
      ]],
    []
  ],
  [
    "11122122",
    [[
        /* Misc */0,
        "Bebop Dominant"
      ]],
    []
  ],
  [
    "11212212",
    [[
        /* Misc */0,
        "Bebop Major"
      ]],
    []
  ],
  [
    "111112122",
    [
      [
        /* Misc */0,
        "Melodic Minor"
      ],
      [
        /* MiddleEast */5,
        "Nahawand"
      ]
    ],
    []
  ],
  [
    "111111111111",
    [[
        /* Misc */0,
        "Chromatic"
      ]],
    []
  ]
];

export {
  namedSpecies ,
}
/* No side effect */
