// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Int from "rescript/lib/es6/belt_Int.js";
import DataJs from "./data.js";
import * as Belt_Array from "rescript/lib/es6/belt_Array.js";
import * as Belt_MapInt from "rescript/lib/es6/belt_MapInt.js";
import * as Belt_Option from "rescript/lib/es6/belt_Option.js";
import * as Belt_MapString from "rescript/lib/es6/belt_MapString.js";
import * as Belt_SortArray from "rescript/lib/es6/belt_SortArray.js";

function any(a, test) {
  return Belt_Array.reduce(a, false, (function (acc, element) {
                if (acc) {
                  return true;
                } else {
                  return Curry._1(test, element);
                }
              }));
}

function DataGeneration$CollapsedTri(Props) {
  var render = Props.render;
  var match = React.useState(function () {
        return /* One */0;
      });
  return Curry._2(render, match[0], match[1]);
}

var CollapsedTri = {
  make: DataGeneration$CollapsedTri
};

var Config = {
  bits: 12
};

function padLeft(_s, l, pad) {
  while(true) {
    var s = _s;
    if (s.length >= l) {
      return s;
    }
    _s = pad + s;
    continue ;
  };
}

function stringToStringArray(x) {
  return Array.from(x);
}

function stringArrayToString(x) {
  return Belt_Array.reduce(x, "", (function (acc, value) {
                return acc + value;
              }));
}

function stringArrayToIntArray(x) {
  return Belt_Array.map(x, (function (x) {
                return Belt_Option.getWithDefault(Belt_Int.fromString(x), 0);
              }));
}

function stringToIntArray(x) {
  return stringArrayToIntArray(Array.from(x));
}

function intArrayToString(x) {
  return Belt_Array.reduce(x, "", (function (acc, value) {
                return acc + String(value);
              }));
}

function stringArrayToInt(x) {
  return Belt_Array.reduceWithIndex(Belt_Array.reverse(x), 0, (function (acc, value, i) {
                return Belt_Option.mapWithDefault(Belt_Int.fromString(value), acc, (function (valueInt) {
                              return (valueInt * Math.pow(2, i) | 0) + acc | 0;
                            }));
              }));
}

function stringToInt(x) {
  return stringArrayToInt(Array.from(x));
}

var BitOps = {
  stringToStringArray: stringToStringArray,
  stringArrayToString: stringArrayToString,
  stringArrayToIntArray: stringArrayToIntArray,
  stringToIntArray: stringToIntArray,
  intArrayToString: intArrayToString,
  stringArrayToInt: stringArrayToInt,
  stringToInt: stringToInt
};

function getPermutationsGivenBitLength(numOfBits) {
  return Belt_Array.map(Belt_Array.range(0, Math.pow(2, numOfBits) - 1 | 0), (function (x) {
                return padLeft(x.toString(2), numOfBits, "0");
              }));
}

function getBinaryHammingWeight(bitArray) {
  return Belt_Array.reduce(bitArray, 0, (function (acc, value) {
                if (value === "1") {
                  return acc + 1 | 0;
                } else {
                  return acc;
                }
              }));
}

function groupByGenus(x) {
  return Belt_Array.reduce(x, undefined, (function (acc, value) {
                var genus = getBinaryHammingWeight(value);
                return Belt_MapInt.update(acc, genus, (function (a) {
                              return Belt_Option.mapWithDefault(a, [value], (function (b) {
                                            return Belt_Array.concat(b, [value]);
                                          }));
                            }));
              }));
}

function rotate(_x, _shift) {
  while(true) {
    var shift = _shift;
    var x = _x;
    if (shift <= 0) {
      return x;
    }
    _shift = shift - 1 | 0;
    _x = Belt_Array.concat(x.slice(1), [Belt_Array.getExn(x, 0)]);
    continue ;
  };
}

function getRotations(x) {
  var unordered = Belt_Array.map(Belt_Array.range(0, x.length - 1 | 0), (function (i) {
          return rotate(x, i);
        }));
  Belt_Array.concat([Belt_Array.getExn(unordered, 0)], Belt_Array.reverse(unordered.slice(1)));
  return Belt_Array.concat([Belt_Array.getExn(unordered, 0)], unordered.slice(1));
}

function getGreatestRotation(x) {
  var rotations = getRotations(x);
  return Belt_Array.reduce(rotations, Belt_Array.getExn(rotations, 0), (function (acc, value) {
                var valueDecRep = stringArrayToInt(value);
                var accDecRep = stringArrayToInt(acc);
                if (valueDecRep > accDecRep) {
                  return value;
                } else {
                  return acc;
                }
              }));
}

function startsWith1(a) {
  return Belt_Array.getExn(a, 0) === "1";
}

function removeZeroStarts(x) {
  return Belt_Array.keep(x, startsWith1);
}

function removeDuplicates(x) {
  return Belt_Array.map(Belt_MapString.keysToArray(Belt_MapString.fromArray(Belt_Array.map(x, (function (a) {
                            return [
                                    stringArrayToString(a),
                                    ""
                                  ];
                          })))), (function (a) {
                return Array.from(a);
              }));
}

function isSameArray(a, b) {
  return Belt_Array.every(Belt_Array.zip(a, b), (function (param) {
                return param[0] === param[1];
              }));
}

function hasBilateralSymmetry(x) {
  var l = x.length;
  if (l % 2 === 0) {
    var a = x.slice(1, l / 2 | 0);
    var b = Belt_Array.reverse(x.slice((l / 2 | 0) + 1 | 0));
    var c = x.slice(0, l / 2 | 0);
    var d = Belt_Array.reverse(x.slice(l / 2 | 0));
    if (isSameArray(a, b)) {
      return true;
    } else {
      return isSameArray(c, d);
    }
  }
  var a$1 = x.slice(1, (l + 1 | 0) / 2 | 0);
  var b$1 = x.slice((l + 1 | 0) / 2 | 0);
  return isSameArray(a$1, Belt_Array.reverse(b$1));
}

function mapAppend(m, k, v) {
  return Belt_MapString.update(m, k, (function (a) {
                return Belt_Option.mapWithDefault(a, [v], (function (b) {
                              return Belt_Array.concat(b, [v]);
                            }));
              }));
}

function groupBySpecies(genusGrouping) {
  return Belt_MapInt.map(genusGrouping, (function (genusPerms) {
                return Belt_MapString.mapWithKey(Belt_MapString.fromArray(Belt_Array.map(Belt_MapString.keysToArray(Belt_Array.reduce(genusPerms, undefined, (function (acc, value) {
                                              var greatestRotation = stringArrayToString(getGreatestRotation(value));
                                              return mapAppend(acc, greatestRotation, value);
                                            }))), (function (speciesId) {
                                      var rotations = getRotations(Array.from(speciesId));
                                      var modes = Belt_SortArray.stableSortBy(Belt_MapString.toArray(Belt_Array.reduceWithIndex(rotations, undefined, (function (acc, value, index) {
                                                      return mapAppend(acc, stringArrayToString(value), index);
                                                    }))), (function (param, param$1) {
                                              return Belt_Array.getExn(param[1], 0) - Belt_Array.getExn(param$1[1], 0) | 0;
                                            }));
                                      return [
                                              speciesId,
                                              modes
                                            ];
                                    }))), (function (speciesId, modes) {
                              var rotations = getRotations(Array.from(speciesId));
                              return {
                                      modes: modes,
                                      autoCorrelations: Belt_Option.mapWithDefault(Belt_Array.get(modes, 0), [], (function (param) {
                                              var modeId = param[0];
                                              return Belt_Array.map(rotations, (function (p) {
                                                            if (stringArrayToString(p) === modeId) {
                                                              return "_";
                                                            } else {
                                                              return String(Belt_Array.keep(Belt_Array.zip(p, Array.from(modeId)), (function (param) {
                                                                                if (param[0] === "1") {
                                                                                  return param[1] === "1";
                                                                                } else {
                                                                                  return false;
                                                                                }
                                                                              })).length);
                                                            }
                                                          }));
                                            })),
                                      isSymmetric: any(rotations, hasBilateralSymmetry)
                                    };
                            }));
              }));
}

var data = DataJs;

var result = Belt_MapInt.fromArray(Belt_Array.map(data, (function (param) {
            return [
                    param[0],
                    Belt_MapString.fromArray(param[1])
                  ];
          })));

export {
  any ,
  CollapsedTri ,
  Config ,
  padLeft ,
  BitOps ,
  getPermutationsGivenBitLength ,
  getBinaryHammingWeight ,
  groupByGenus ,
  rotate ,
  getRotations ,
  getGreatestRotation ,
  startsWith1 ,
  removeZeroStarts ,
  removeDuplicates ,
  isSameArray ,
  hasBilateralSymmetry ,
  mapAppend ,
  groupBySpecies ,
  data ,
  result ,
}
/* data Not a pure module */
